project 'hotty.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hotty' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Firebase/Core'
  pod 'SwiftyJSON'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Analytics'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'
  pod 'GooglePlaces'
  
end
